qlf_k6n10: temporarily disable toolchain tests
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>

diff --git a/quicklogic/common/toolchain_wrappers/ql_symbiflow b/quicklogic/common/toolchain_wrappers/ql_symbiflow
--- a/quicklogic/common/toolchain_wrappers/ql_symbiflow
+++ b/quicklogic/common/toolchain_wrappers/ql_symbiflow
@@ -21,7 +21,9 @@ echo -e "\nBelow are the supported commands: \n\
 \t>ql_symbiflow -synth -src <source_dir path> -d <device> -P <pinmap csv file> -t <top module name> -v <verilog file/files> -p <pcf file>\n\
  To run synthesis, pack, place and route:\n\
 \t>ql_symbiflow -compile -src <source_dir path> -d <device> -P <pinmap csv file> -t <top module name> -v <verilog file/files> -p <pcf file> -P <pinmap csv file> -s <SDC file> \n\
-Devices supported: ql-eos-s3, ql-pp3, qlf_k4n8, qlf_k6n10 " || exit
+Devices supported: ql-eos-s3, ql-pp3, qlf_k4n8 \n\
+Support temporarily disabled for: qlf_k6n10" || exit
+
 elif [[ $1 == "-v" || $1 == "--version" ]];then
         echo "Symbiflow Tool Version : ${VERSION}"
         exit
@@ -244,7 +246,8 @@ if [[ $1 == "-compile" || $1 == "-post_verilog" ]]; then
     echo "DEVICE name is missing. Refer -h/--help"
     exit 1
   elif ! [[ "$DEVICE_CHECK" =~ ^(VALID)$ ]]; then
-	  echo "Invalid Device name, supported: ql-eos-s3, ql-pp3, qlf_k4n8, qlf_k6n10"
+	  echo "Invalid Device name, supported: ql-eos-s3, ql-pp3, qlf_k4n8 \n\
+		Support temporarily disabled for: qlf_k6n10"
     exit 1
   fi
   if [ -z "$TOP" ]; then
