Integrated SDC constraints processing with the installed toolchain
Signed-off-by: Maciej Kurc <mkurc@antmicro.com>

diff --git a/quicklogic/common/toolchain_wrappers/ql_symbiflow b/quicklogic/common/toolchain_wrappers/ql_symbiflow
--- a/quicklogic/common/toolchain_wrappers/ql_symbiflow
+++ b/quicklogic/common/toolchain_wrappers/ql_symbiflow
@@ -499,17 +499,22 @@ else
     PCF_MAKE="\${current_dir}/build/${TOP}_dummy.pcf"
 fi
 
+PROCESS_SDC=`realpath ${MYPATH}/python/process_sdc_constraints.py`
 if ! [ -z "$SDC" ]; then
-	if ! [ -f "$SOURCE"/$SDC ];then
-            echo "The sdc file: $SDC is missing at: $SOURCE"
-            exit 1
-         else
-	    SDC_MAKE="\${current_dir}/$SDC"
-	    cp ${CURR_DIR}/$SDC ${CURR_DIR}/build/${TOP}.sdc
-         fi
+    if ! [ -f "$SOURCE"/$SDC ];then
+        echo "The sdc file: $SDC is missing at: $SOURCE"
+        exit 1
+    else
+        SDC_MAKE="\${current_dir}/build/${TOP}.sdc"
+        if [ -f "$SOURCE"/$PCF_FILE ];then
+            python3 ${PROCESS_SDC} --sdc-in ${CURR_DIR}/${SDC} --pcf ${CURR_DIR}/${PCF} --sdc-out ${CURR_DIR}/build/${TOP}.sdc
+        else
+            cp ${CURR_DIR}/${SDC} ${CURR_DIR}/build/${TOP}.sdc
+        fi
+    fi
 else
-  	 touch ${CURR_DIR}/build/${TOP}_dummy.sdc
-   	 SDC_MAKE="\${current_dir}/build/${TOP}_dummy.sdc"
+    touch ${CURR_DIR}/build/${TOP}_dummy.sdc
+    SDC_MAKE="\${current_dir}/build/${TOP}_dummy.sdc"
 fi
 
 
